function report=q1_compare_freezing(root)
% Diagnostic structural comparison. Nucleation thresholds are hypotheses.
if nargin<1,root=fileparts(fileparts(mfilename('fullpath')));end
base=q1_config(); [cases,~]=q1_read_data(root,base);
specs={ ...
    'direct_ice',struct(); ...
    'delayed_threshold_0p20',struct('freezingClosure','delayed_nucleation', ...
        'liquidMigration',true,'nucleationThreshold',.20); ...
    'delayed_threshold_0p03',struct('freezingClosure','delayed_nucleation', ...
        'liquidMigration',true,'nucleationThreshold',.03)};
rows=cell(0,11);
for z=1:size(specs,1)
    c=base; f=fieldnames(specs{z,2});
    for j=1:numel(f),c.(f{j})=specs{z,2}.(f{j});end
    for k=1:2
        d=cases(k); run=q1_simulate(d,c,'coarse');
        ice=[run.obs.ice_volume_max]';
        i=find(ice>1e-6,1); onset=NaN;
        if ~isempty(i),onset=run.obs(i).time_s;end
        V=[run.obs.V_sim]'; T=[run.obs.T_seven_C]';
        rows(end+1,:)={string(specs{z,1}),string(d.name),string(run.status), ...
            onset,max(ice),max([run.obs.ice_saturation_max]), ...
            max([run.obs.liquid_saturation_max]), ...
            sqrt(mean((V-d.V_exp).^2)),sqrt(mean((T-d.T_exp_C).^2)), ...
            run.balance.ew,run.balance.eE}; %#ok<AGROW>
    end
end
report=cell2table(rows,'VariableNames',{'closure','case_name','status', ...
    'ice_onset_s','ice_absolute_peak','ice_saturation_peak', ...
    'liquid_saturation_peak','V_RMSE','T_RMSE_C','water_error','energy_error'});
folder=fullfile(root,'results','checks');if ~isfolder(folder),mkdir(folder);end
writetable(report,fullfile(folder,'freezing_structure_comparison.csv'));
end
