function report=q1_diagnose_voltage(root)
if nargin<1,root=fileparts(fileparts(mfilename('fullpath')));end
base=q1_config(); [d,~]=q1_read_data(root,base);
kin=q1_fit_kinetics(d,base);
scenarios={ ...
    'default',struct(); ...
    'Ea67_j0_025_fCL3',struct('j0ref',.25,'fCL',3); ...
    'Ea67_no_ice_feedback',struct('j0ref',.25,'fCL',3,'iceFeedback',false); ...
    'low_current_kinetics',struct('Ea',kin.Ea_Jmol,'j0ref',kin.j0_298); ...
    'low_current_no_ice_feedback',struct('Ea',kin.Ea_Jmol,'j0ref',kin.j0_298,'iceFeedback',false); ...
    'parallel_active',struct('j0ref',.25,'reactionClosure','parallel_active'); ...
    'parallel_hydration_beta2',struct('j0ref',.25,'reactionClosure','parallel_active', ...
        'kineticHydrationExponent',2); ...
    'Ea_fit_parallel_hydration',struct('Ea',kin.Ea_Jmol,'j0ref',kin.j0_298, ...
        'reactionClosure','parallel_active','kineticHydrationExponent',2)};
rows=cell(0,11); windows=[0 6;6 15;15 36.6];
for k=1:size(scenarios,1)
    c=base; fn=fieldnames(scenarios{k,2});
    for z=1:numel(fn),c.(fn{z})=scenarios{k,2}.(fn{z});end
    for ci=1:2
        run=q1_simulate(d(ci),c,'coarse');
        if numel(run.obs)~=numel(d(ci).t),continue;end
        V=[run.obs.V_sim]'; T=[run.obs.T_seven_C]'; t=d(ci).t;
        [minV,ix]=min(V); [minVe,ixe]=min(d(ci).V_exp);
        wr=zeros(1,3);
        for z=1:3
            m=t>=windows(z,1)-1e-9 & t<=windows(z,2)+1e-9;
            wr(z)=sqrt(mean((V(m)-d(ci).V_exp(m)).^2));
        end
        rows(end+1,:)={string(scenarios{k,1}),string(d(ci).name), ...
            string(run.status),sqrt(mean((V-d(ci).V_exp).^2)), ...
            sqrt(mean((T-d(ci).T_exp_C).^2)), ...
            wr(1),wr(2),wr(3),V(end)-d(ci).V_exp(end),t(ix)-t(ixe), ...
            minV-minVe}; %#ok<AGROW>
    end
end
report=cell2table(rows,'VariableNames',{'scenario','case_name','status','V_RMSE', ...
    'T_RMSE_C','V_RMSE_0_6','V_RMSE_6_15','V_RMSE_15_end', ...
    'V_end_bias','valley_time_error_s','valley_voltage_error'});
folder=fullfile(root,'results','checks'); if ~isfolder(folder),mkdir(folder);end
writetable(report,fullfile(folder,'voltage_diagnosis.csv'));
end
